# Generated by Django 5.2.5 on 2025-08-24 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件路径')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件传输',
                'verbose_name_plural': '文件传输',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
